version: "3.9"

x-logging:
  &default-logging
  driver: loki
  options:
    loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

networks:
  web:
    external: true
  internal:
    external: true
  default:
    external: true
    name: internal

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./data/fdroid:/fdroid
      - ./data/app-store-review-feed:/app-store-review-feed/
    networks:
      - web
      - internal

  postgres:
    image: supabase/postgres:13.3.0
    container_name: postgres
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - secrets/postgres.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  clickhouse:
    image: yandex/clickhouse-server:21.3.2.5
    container_name: clickhouse
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v1.4
    container_name: plausible
    restart: unless-stopped
    logging: *default-logging
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - postgres
      - clickhouse
    env_file:
      - plausible/plausible.env
      - secrets/plausible.env

  # Used by plausible
  mail:
    image: bytemark/smtp
    restart: unless-stopped
    logging: *default-logging

  listmonk:
    image: listmonk/listmonk:v2.0.0
    container_name: listmonk
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./secrets/listmonk.config.toml/:/listmonk/config.toml
    depends_on:
      - postgres

  # listmonk_install:
  #   image: listmonk/listmonk:v2.0.0
  #   command: ["sh", "-c", "yes | ./listmonk --install"]
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./secrets/listmonk.config.toml/:/listmonk/config.toml

  # listmonk_upgrade:
  #   image: listmonk/listmonk:v2.0.0
  #   command: ["sh", "-c", "yes | ./listmonk --upgrade"]
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./secrets/listmonk.config.toml/:/listmonk/config.toml

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    depends_on:
      - cadvisor

  node-exporter:
    image: prom/node-exporter
    container_name: prom_node_exporter
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  alertmanager:
    image: prom/alertmanager
    container_name: prom_alertmanager
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"

  cadvisor:
    image: google/cadvisor
    container_name: prom_cadvisor
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana:8.2.0
    container_name: grafana
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.env
      - ./secrets/grafana.env
    user: "472"

  loki:
    image: grafana/loki:2.3.0
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - ./data/loki:/data/
    ports:
      - "127.0.0.1:3100:3100" # Docker logging

  promtail:
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - loki
    volumes:
      - /var/log:/var/log:ro
      - /run/log/journal:/run/log/journal:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./promtail:/etc/promtail-config:ro
      - ./data/promtail:/data/
    command: -config.file=/etc/promtail/config.yml

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - postgres
    env_file:
      - ./secrets/n8n.env
    volumes:
      - ./data/apks:/apks/
      - ./data/n8n:/home/node/.n8n
    command: n8n start

# Supabase Containers
  kong:
    image: kong:2.1
    container_name: supabase-kong
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./secrets/supabase-kong.yml:/var/lib/kong/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth

  auth:
    image: supabase/gotrue:v2.1.8
    container_name: supabase-auth
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - postgres
    env_file:
      - ./secrets/supabase-auth.env

  rest:
    image: postgrest/postgrest:v8.0.0
    container_name: supabase-rest
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - postgres
    env_file:
      - ./secrets/supabase-rest.env

  realtime:
    image: supabase/realtime:v0.15.0
    container_name: supabase-realtime
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - postgres
    env_file:
      - ./secrets/supabase-realtime.env

  storage:
    image: supabase/storage-api:v0.9.3
    container_name: supabase-storage
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - postgres
      - rest
    volumes:
      - ./data/supabase/storage:/var/lib/storage
    env_file:
      - ./secrets/supabase-storage.env


  # db:
  #   container_name: supabase-db
  #   image: supabase/postgres:13.3.0
  #   restart: unless-stopped
  #   ports:
  #     - ${POSTGRES_PORT}:5432
  #   volumes:
  #     - ./volumes/db/data:/var/lib/postgresql/data
  #     - ./volumes/db/init:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   command: postgres -c wal_level=logical

  app-store-reviews:
    image: ghcr.io/gitjournal/app-store-review-feed
    container_name: app-store-review-feed
    restart: unless-stopped
    logging: *default-logging
    volumes:
      - ./data/app-store-review-feed/:/data