version: "3"

services:
  reverse-proxy:
    image: traefik:v2.3
    restart: always
    command:
      - --api.dashboard=false
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=gitjournal.io@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
      - --entryPoints.metrics.address=:8082
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/acme:/etc/traefik/acme

  postgres:
    image: postgres:12
    restart: always
    env_file:
      - secrets/postgres.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # gotrue_migrate:
  #   image: ghcr.io/gitjournal/gotrue
  #   command: gotrue migrate
  #   env_file:
  #     - gotrue.env
  #     - secrets/gotrue.env
  #   depends_on:
  #     - postgres

  gotrue:
    image: ghcr.io/gitjournal/gotrue
    restart: always
    env_file:
      - gotrue.env
      - secrets/gotrue.env
    depends_on:
      - postgres
    labels:
      - "traefik.http.routers.gotrue.rule=Host(`api.gitjournal.io`) && PathPrefix(`/auth/`)"
      - "traefik.http.routers.gotrue.tls=true"
      - "traefik.http.routers.gotrue.tls.certresolver=myresolver"
      - "traefik.http.routers.gotrue.middlewares=gotrue-stripprefix"
      - "traefik.http.middlewares.gotrue-stripprefix.stripprefix.prefixes=/auth"
      - "traefik.http.middlewares.gotrue-stripprefix.stripprefix.forceSlash=false"
      - "traefik.http.services.gotrue.loadbalancer.server.port=9999"

  listmonk:
    image: listmonk/listmonk:v0.8.0-beta
    restart: unless-stopped
    ports:
      - "9128:9128"
    volumes:
      - ./secrets/listmonk.config.toml/:/listmonk/config.toml
    depends_on:
      - postgres
    labels:
      - "traefik.http.routers.listmonk.rule=Host(`listmonk.gitjournal.io`)"
      - "traefik.http.routers.listmonk.tls=true"
      - "traefik.http.routers.listmonk.tls.certresolver=myresolver"
      - "traefik.http.services.listmonk.loadbalancer.server.port=9999"

  # listmonk_install:
  #   image: listmonk/listmonk:v0.8.0-beta
  #   restart: unless-stopped
  #   command: ["sh", "-c", "yes | ./listmonk --install"]
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./secrets/listmonk.config.toml/:/listmonk/config.toml
